version: '3.9'
services:
  reverse-proxy:
    image: lakleij/aurum-capital-partners-reverse-proxy
    ports:
      - 80:80
    depends_on:
      - frontend
  frontend:
    image: lakleij/aurum-capital-partners
    ports:
      - 8100:8100